export const ORIGIN_ENDPOINT = process.env.NEXT_PUBLIC_ORIGIN_ENDPOINT || "";

// web admin API
export const ADMIN_USERS_ENDPOINT =
  process.env.NEXT_PUBLIC_ADMIN_USERS_ENDPOINT || "";

export const ADMIN_STORES_ENDPOINT =
  process.env.NEXT_PUBLIC_ADMIN_STORES_ENDPOINT || "";

export const ADMIN_PRODUCTS_ENDPOINT =
  process.env.NEXT_PUBLIC_ADMIN_PRODUCTS_ENDPOINT || "";

export const ADMIN_STATES_ENDPOINT =
  process.env.NEXT_PUBLIC_ADMIN_STATES_ENDPOINT || "";

export const ADMIN_DISTRICTS_ENDPOINT =
  process.env.NEXT_PUBLIC_ADMIN_DISTRICTS_ENDPOINT || "";

export const ADMIN_BUSINESS_CATEGORY_ENDPOINT =
  process.env.NEXT_PUBLIC_ADMIN_BUSINESS_CATEGORY_ENDPOINT || "";

export const ADMIN_LICENSE_TYPE_ENDPOINT =
  process.env.NEXT_PUBLIC_ADMIN_LICENSE_TYPE_ENDPOINT || "";

// react-native API
export const USER_ENDPOINT = process.env.NEXT_PUBLIC_USER_ENDPOINT || "";
